name: speed_test_dart
description: Internet speed tester (ping, upload, download) using speedtest.net
version: 1.0.6+0
homepage: https://github.com/jorger5/speed_test_dart
repository: https://github.com/jorger5/speed_test_dart

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies: 
  http: ^1.5.0
  sync: ^0.3.0
  xml: ^6.5.0


dev_dependencies:
  very_good_analysis: ^9.0.0


